### Регистрация пользователя
POST http://localhost:8080/api/profiles
Content-Type: application/json

{
  "firstName": "Иванв",
  "lastName": "Ивановв",
  "email": "ivan@examp.com",
  "username": "iva",
  "password": "passwo"
}

### Вход в систему (получение токена)
POST http://localhost:8080/auth/signin
Content-Type: application/json

{
  "username": "iva",
  "password": "passwo"
}
